FROM openjdk:17-jdk-alpine

RUN mkdir /files

COPY target/SpringBootProvider-0.0.1-SNAPSHOT.jar SpringBoot_Provider.jar

RUN chmod -R 777 /files

WORKDIR /

ENTRYPOINT ["java", "-jar", "/SpringBoot_Provider.jar"]