FROM openjdk:17-jdk-alpine

RUN mkdir /files

COPY target/SpringBootConsumer-0.0.1-SNAPSHOT.jar SpringBoot_Consumer.jar

RUN chmod -R 777 /files

WORKDIR /

ENTRYPOINT ["java", "-jar", "/SpringBoot_Consumer.jar"]